import datetime

redirect('<LOGPATH>/current.log')
connect ('USERID','PASSWORD','t3://<SERVER>:<PORT>')
domainRuntime()

print ("Stats before GC():")
cd('/ServerRuntimes/PIA1/JVMRuntime/PIA1')
print("JVM Heap Free:" + str(cmo.getHeapFreeCurrent()))
print("JVM Heap Free Percentage:"+str(cmo.getHeapFreePercent()))
print("JVM Size Current:"+str(cmo.getHeapSizeCurrent()))
cd ('/')
cd('/ServerRuntimes/PIA1/ApplicationRuntimes/peoplesoft/ComponentRuntimes/PIA1_')
print("Current Session Count:" + str(cmo.getOpenSessionsCurrentCount()))
print("cookie name:" + cmo.getSessionCookieName())
print("Sessions :")
print(cmo.getServletSessionsMonitoringIds())
print("starting to run GC")
cd ('/')
cd('/ServerRuntimes/PIA1/JVMRuntime/PIA1')
cmo.runGC()
print("GC completed. Stats after:")
cd('/ServerRuntimes/PIA1/JVMRuntime/PIA1')
print("JVM Heap Free:" + str(cmo.getHeapFreeCurrent()))
print("JVM Heap Free Percentage:"+str(cmo.getHeapFreePercent()))
print("JVM Size Current:"+str(cmo.getHeapSizeCurrent()))
cd ('/')
cd('/ServerRuntimes/PIA1/ApplicationRuntimes/peoplesoft/ComponentRuntimes/PIA1_')
print("Current Session Count:" + str(cmo.getOpenSessionsCurrentCount()))
print("cookie name:" + cmo.getSessionCookieName())
print("Sessions :")
print(cmo.getServletSessionsMonitoringIds())
print("starting to run GC")

exit()
